baseurl = "https://wogri.github.io"
DefaultContentLanguage = "en"
title = "Junge Gemeinde"
# Using theme as git submodule 
theme = "beautifulhugo"
# Or when using theme as hugo module
# theme = "github.com/halogenica/beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"

[Services]
  [Services.Disqus]
    # Shortname = "XXX"
  [Services.googleAnalytics]
    # id = "XXX"

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "Handybewusste Gemeinde Luftenberg"
  mainSections = ["post","posts"]
  logo = "img/avatar-icon.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
#  cusdisID = "XXX" # Get your App id from cusdis.com
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
#  disclaimerText = "The opinions expressed herein are my own personal opinions and do not represent my employer’s view in any way."

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Params.author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "Junge Gemeinde Luftenberg"
  website = "yourwebsite.com"
  email = "youremail@domain.com"
  facebook = "username"

[[menu.main]]
    identifier = "samples"
    name = "Google Drive Dateien"
    weight = 2

[[menu.main]]
    parent = "samples"
    name = "Für Mitwirkende der jungen Gemeinde"
    url = "https://docs.google.com/spreadsheets/d/14b6WZsmMQMlD_dmv2eVY5lsUUpD6MRvI0guTIpukvY8/edit?gid=0#gid=0"
    weight = 1

[[menu.main]]
    parent = "samples"
    name = "Für Vereine"
    url = "https://docs.google.com/spreadsheets/d/14b6WZsmMQMlD_dmv2eVY5lsUUpD6MRvI0guTIpukvY8/edit?gid=0#gid=0"
    weight = 2

[[menu.main]]
    parent = "samples"
    name = "Für Veranstalter"
    url = "https://docs.google.com/spreadsheets/d/14b6WZsmMQMlD_dmv2eVY5lsUUpD6MRvI0guTIpukvY8/edit?gid=0#gid=0"
    weight = 2
